routes:
- max_time: 12
  min_time: 4
  plan_id: '403640128840458306'
  route_distance_km: 1.2
  route_name: 丁家桥体育场
  route_rule: 丁家桥校区
  rule_end_time: '22:00'
  rule_id: '403640128840458304'
  rule_start_time: 06:00
- max_time: 12
  min_time: 4
  plan_id: '403640128840458521'
  route_distance_km: 1.2
  route_name: 四牌楼体育场
  route_rule: 四牌楼校区
  rule_end_time: '22:00'
  rule_id: '403640128840458519'
  rule_start_time: 06:00
- max_time: 12
  min_time: 4
  plan_id: '403640128840458727'
  route_distance_km: 1.2
  route_name: 小营田径场
  route_rule: 四牌楼校区
  rule_end_time: '22:00'
  rule_id: '403640128840458519'
  rule_start_time: 06:00
- max_time: 12
  min_time: 4
  plan_id: '405863869632939014'
  route_distance_km: 1.2
  route_name: 无锡国际校区体育馆
  route_rule: 无锡国际校区
  rule_end_time: '22:00'
  rule_id: '482716833313089537'
  rule_start_time: 06:00
- max_time: 12
  min_time: 4
  plan_id: '403640124545491473'
  route_distance_km: 1.2
  route_name: 桃园田径场
  route_rule: 九龙湖校区
  rule_end_time: '22:00'
  rule_id: '402186368309502988'
  rule_start_time: 06:00
- max_time: 12
  min_time: 4
  plan_id: '403640115955556355'
  route_distance_km: 1.2
  route_name: 梅园田径场
  route_rule: 九龙湖校区
  rule_end_time: '22:00'
  rule_id: '402186368309502988'
  rule_start_time: 06:00
- max_time: 12
  min_time: 4
  plan_id: '403640124545491749'
  route_distance_km: 1.2
  route_name: 橘园田径场
  route_rule: 九龙湖校区
  rule_end_time: '22:00'
  rule_id: '402186368309502988'
  rule_start_time: 06:00
